### ISSUE TITLE
Please Start

### ISSUE THREAD

**Issue by indrazm** [sarasseres/Project-Syntex#1]
Hey @sarasseres @lutfinoorm @Rahmasafff 
Please start adding action items to project, and convert to issue. 
Let me know if you guys need help.

**Comment by sarasseres** [comment]
Build Next Js Boilerplate
1. Setup Next Js
2. Make a Sructure in Next Js 
3. Make Component in Next Js

**Comment by lutfinoorm** [comment]
saya sedang coba pelajari bagaimana make a clone, rencananya ingin membuat branch baru. tapi belum bisa.

**Comment by lutfinoorm** [comment]
> Build Next Js Boilerplate
> 
>     1. Setup Next Js
> 
>     2. Make a Sructure in Next Js
> 
>     3. Make Component in Next Js

sepertinya yang Mba @sarasseres bikin sebelumnya, ini. lebih tepat kalau jadi issue yang baru ya mas @indrazm?

**Comment by lutfinoorm** [comment]
![image](https://github.com/sarasseres/Project-Syntex/assets/126556211/f70572dd-aa8a-4ac9-95e2-0501b4d3fa11)

Apa semua issue yang Mas @indrazm tulis di project 'Eventmakers' milik Mas Indra, dapat di copy paste ke project synthex?

**Comment by indrazm** [comment]
Betul @lutfinoorm , bisa di copy paste, nanti saya bantu koreksi.

**Comment by sarasseres** [comment]
1. create Login Page Functionality

**Comment by Rahmasafff** [comment]
2. create register page ui
