### ISSUE TITLE
Build Shared UI

### ISSUE THREAD

**Issue by sarasseres** [sarasseres/Project-Syntex#3]

**Comment by indrazm** [comment]
Do we need to create UI Component or using Library such as DaisyUI ?

**Comment by lutfinoorm** [comment]
In my opinion using it will cut much time to designing the layout rather than making from scratch. But, I've never done project using DaisyUI, Mas. 

Maybe Mba @sarasseres and @Rahmasafff have their opinion.

**Comment by indrazm** [comment]
Agreed.
I suggest to use DaisyUI. Okey. Please start to work on Login UI Then. 
You don't need to create Shared UI.

**Comment by lutfinoorm** [comment]
![image](https://github.com/sarasseres/Project-Syntex/assets/126556211/da4d30d5-ce83-4217-a78f-bd54a9da9254)

I've added login UI. Please, kindly check the code i write. 
Kind regards,

PS:
I'll try to make it better tomorrow or day after, insyaAllah.

**Comment by sarasseres** [comment]
i think this is more than enough good job mas lutfi

**Comment by indrazm** [comment]
@lutfinoorm Please create PR for code review. Tag me and @sarasseres as reviewer.
